CREATE TABLE dealerships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    region VARCHAR(255) NOT NULL
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(100) NOT NULL,
    preferred_dealership_id BIGINT,
    CONSTRAINT fk_customers_dealership FOREIGN KEY (preferred_dealership_id) REFERENCES dealerships(id)
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin VARCHAR(255) NOT NULL UNIQUE,
    model VARCHAR(255) NOT NULL,
    family VARCHAR(255) NOT NULL,
    model_year INTEGER NOT NULL,
    mileage INTEGER NOT NULL,
    customer_id BIGINT NOT NULL,
    dealership_id BIGINT NOT NULL,
    warranty_end_date DATE,
    health_status VARCHAR(100) NOT NULL,
    CONSTRAINT fk_vehicles_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_vehicles_dealership FOREIGN KEY (dealership_id) REFERENCES dealerships(id)
);

CREATE TABLE service_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    dealership_id BIGINT NOT NULL,
    service_type VARCHAR(255) NOT NULL,
    service_date DATE NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_service_records_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_service_records_dealership FOREIGN KEY (dealership_id) REFERENCES dealerships(id)
);

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    vehicle_id BIGINT,
    dealership_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    urgency VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    source VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    converted_at TIMESTAMP,
    CONSTRAINT fk_leads_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_leads_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_leads_dealership FOREIGN KEY (dealership_id) REFERENCES dealerships(id)
);

CREATE TABLE stock_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealership_id BIGINT NOT NULL,
    part_name VARCHAR(255) NOT NULL,
    vehicle_family VARCHAR(255) NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    forecast_demand INTEGER NOT NULL,
    alert_level VARCHAR(50) NOT NULL,
    CONSTRAINT fk_stock_items_dealership FOREIGN KEY (dealership_id) REFERENCES dealerships(id)
);

CREATE TABLE assistant_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    input_text VARCHAR(1000) NOT NULL,
    detected_topic VARCHAR(255) NOT NULL,
    recommendation VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_assistant_interactions_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

